carts/urls.py
from . import views
from django.shortcuts import render
from django.urls import path

urlpatterns = [
    path('', views.cart_home, name="cart_home"),
    path('update/', views.cart_update, name="cart_update"),
    path('checkout/', views.checkout_home, name="checkout"),
    path('checkout/success', views.checkout_done_view, name="success"),
    path('api/cart/', views.cart_detail_api_view, name="api_cart")
]

products/urls.py
from django.urls import path
from . import views
from products.views import (ProductListView,
                        # product_list_view,
                        # ProductDetailView,
                        # product_detail_view,
                        # ProductFeaturedListView,
                        # ProductFeaturedDetailView,
                        ProductDetailSlugView,
)

app_name = 'products'
urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug>/', ProductDetailSlugView.as_view(), name='detail'),
]

retail_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic.base import RedirectView



urlpatterns = [
    path('', views.home_page, name='home'),
    path('admin/', admin.site.urls),
    path('about/', views.about_page, name='about'),
    path('contact/', views.contact_page, name='contact'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('search/', include('search.urls')),
    path('cart/', include('carts.urls')),
    path('addresses/', include('addresses.urls')),
    path('billing/', include('billing.urls')),
    path('marketing/', include('marketing.urls')),
    # paths for user account settings
    path('account/', RedirectView.as_view(url='/accounts/login_home')),
    path('settings/', RedirectView.as_view(url='/accounts/login_home')),
    path('accounts/', include('accounts.passwords.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about_page.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">About:</h1>
      <p class="lead">Orders placed before 8pm Monday to Thursday or before 4pm Friday to Sunday will be sent next day delivery (except on bank holidays). This is subject to delivery postcode, same day credit/security check approval and stock availability. </p>
    </div>
  </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Hello, world!</title>
  {% include "base/css.html" %}
  {% block base_head %}
  {% endblock %}
</head>

<body>
  {% include "base/navbar.html" with brand_name="eCommerce" %}
  {% include "base/js.html" %}

  <div class="container">
      <!-- Django messages -->
      {% if messages %}
      <div class="alert alert-success messages">
      {% for message in messages %}
      <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}<br/></span>
      {% endfor %}
      </div>
      {% endif %}
      {% block content %}
      {% endblock %}
  </div>

</body>

</html>

templates/contact_page.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="text-center">
    <h1>{{ title }}</h1>
    <h1>Hello!</h1>
    <p>{{ content }}</p>
</div>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="col-md-6 col-12 mx-auto">
                <form class="contact-form" method="POST" action="{% url 'contact' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-info">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/home_page.html
{% extends "base.html" %}
{% load static %}


{% block base_head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
{% url 'products:list' as products_url %}

<div class="homapage">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'img/phone1.jpg'%}" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/phone2.jpg' %}" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/phone3.jpeg' %}" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="text">
        <h1>Hey! Nice to meet you at our best mobile retail store!</h1>
        <a href="{{products_url}}"> Please check our products!</a>
    </div>
</div>

{% endblock %}